# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'j.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from alert import *
from listview import *
from newservice import *
from sql import *
#importing functions from files

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.MainWindow = Dialog

        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 626)
        Dialog.setStyleSheet("")
        self.welcomelabel = QtWidgets.QLabel(Dialog)
        self.welcomelabel.setGeometry(QtCore.QRect(20, 10, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.welcomelabel.setFont(font)
        self.welcomelabel.setObjectName("welcomelabel")
        self.headinglabel = QtWidgets.QLabel(Dialog)
        self.headinglabel.setGeometry(QtCore.QRect(60, 70, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.headinglabel.setFont(font)
        self.headinglabel.setAutoFillBackground(True)
        self.headinglabel.setObjectName("headinglabel")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.usernamelabel = QtWidgets.QLabel(Dialog)
        self.usernamelabel.setGeometry(QtCore.QRect(80, 259, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setObjectName("usernamelabel")
        self.usernamelineedit = QtWidgets.QLineEdit(Dialog)
        self.usernamelineedit.setGeometry(QtCore.QRect(190, 260, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usernamelineedit.setFont(font)
        self.usernamelineedit.setObjectName("usernamelineedit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 560, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.loginpushbutton = QtWidgets.QPushButton(Dialog)
        self.loginpushbutton.setGeometry(QtCore.QRect(280, 390, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginpushbutton.setFont(font)
        self.loginpushbutton.setObjectName("loginpushbutton")
        self.passworlabel = QtWidgets.QLabel(Dialog)
        self.passworlabel.setGeometry(QtCore.QRect(80, 309, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passworlabel.setFont(font)
        self.passworlabel.setObjectName("passworlabel")
        self.passwordlineedit = QtWidgets.QLineEdit(Dialog)
        self.passwordlineedit.setGeometry(QtCore.QRect(190, 310, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordlineedit.setFont(font)
        self.passwordlineedit.setObjectName("passwordlineedit")
        self.extrathingsframe = QtWidgets.QFrame(Dialog)
        self.extrathingsframe.setGeometry(QtCore.QRect(0, 570, 521, 51))
        self.extrathingsframe.setStyleSheet("")
        self.extrathingsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.extrathingsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extrathingsframe.setLineWidth(0)
        self.extrathingsframe.setObjectName("extrathingsframe")
        self.contactuspussbutton = QtWidgets.QPushButton(self.extrathingsframe)
        self.contactuspussbutton.setGeometry(QtCore.QRect(380, 10, 80, 25))
        self.contactuspussbutton.setObjectName("contactuspussbutton")
        self.twitterpushbutton = QtWidgets.QPushButton(self.extrathingsframe)
        self.twitterpushbutton.setGeometry(QtCore.QRect(260, 10, 80, 25))
        self.twitterpushbutton.setObjectName("twitterpushbutton")
        self.helpbutton = QtWidgets.QPushButton(self.extrathingsframe)
        self.helpbutton.setGeometry(QtCore.QRect(20, 10, 80, 25))
        self.helpbutton.setObjectName("helpbutton")
        self.websitpushbutton = QtWidgets.QPushButton(self.extrathingsframe)
        self.websitpushbutton.setGeometry(QtCore.QRect(130, 10, 80, 25))
        self.websitpushbutton.setObjectName("websitpushbutton")
        self.registercheckbox = QtWidgets.QCheckBox(Dialog)
        self.registercheckbox.setGeometry(QtCore.QRect(170, 390, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registercheckbox.setFont(font)
        self.registercheckbox.setObjectName("registercheckbox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        self.loginpushbutton.clicked.connect(
            self.onclickloginpushbutton
        ) 


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcomelabel.setText(_translate("Dialog", "WELCOME To"))
        self.headinglabel.setText(_translate("Dialog", " Sarathi Password Manager"))
        self.label_3.setText(_translate("Dialog", "LOGIN"))
        self.usernamelabel.setText(_translate("Dialog", "USERNAME:"))
        self.loginpushbutton.setText(_translate("Dialog", "Login"))
        self.passworlabel.setText(_translate("Dialog", "PASSWORD:"))
        self.contactuspussbutton.setText(_translate("Dialog", "contact us"))
        self.twitterpushbutton.setText(_translate("Dialog", "twitter"))
        self.helpbutton.setText(_translate("Dialog", "help"))
        self.websitpushbutton.setText(_translate("Dialog", "website"))
        self.registercheckbox.setText(_translate("Dialog", "Register"))
   
    global alert
    def alert(self,alerttext):

        self.window = QtWidgets.QMainWindow()
        self.ui = alertclass()
        self.ui.alertwindow(self.window,alerttext)
        self.window.show()
    global listview
    def listview(self):
        self.MainWindow.close()

        self.window = QtWidgets.QMainWindow()
        self.ui = listviewclass()
        self.ui.listviewwindow(self.window)
        self.window.show()


  


    def onclickloginpushbutton(self):
        def login():
                username=self.usernamelineedit.text()
                password=self.passwordlineedit.text()
                command="select * from login;"
                l=database(command,getoutput=True)
                if (username,password) in l:
                    alert(self,"login successful")
                    listview(self)
                else:
                    alert(self,"pls register")

                    
        def register():
                username=self.usernamelineedit.text()
                password=self.passwordlineedit.text()
                #checking if that same username and password exist
                command="select * from login;"
                l=database(command,getoutput=True)
                if (username,password) not in l:
                    command="insert into login values('"+username+"','"+password+"');"
                    database(command)
                    login()
                else:
                    alert(self,"username and password already exist")

        
        if self.registercheckbox.isChecked()== True:
            register()
        else:
            login()




        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
